# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/classifierPets',
                'doc_host': 'https://hfnhf.github.io',
                'git_url': 'https://github.com/hfnhf/classifierPets',
                'lib_path': 'classifierPets'},
  'syms': {'classifierPets.core': {'classifierPets.core.foo': ('core.html#foo', 'classifierPets/core.py')}}}
